config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'users_controller/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show] do
    member {post :link_spotify}
  end
  resources :playlists, only: [:new, :show]
  resources :bugs
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  root 'pages#home'
  post 'playlists/display' => 'playlists#display', as: :display_playlist

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/help',    to: 'pages#help'
  get  '/callback', to: 'pages#callback'
  get '/positivity', to: 'pages#show_positivity'
  get '/slack', to: 'pages#send_to_slack'

  get '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
  post '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
end

app/models/article.rb
# Article model where relations are
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 128 }
  validates :text, presence: true, length: { maximum: 5000 }
  validates_associated :user
end

app/controllers/articles_controller.rb
# Article controller used for viewing,editing,deleting and creating articles.
class ArticlesController < ApplicationController
  def new
    if current_user && current_user.admin?
      @article = Article.new
    else
      redirect_to root_path
    end
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    if current_user && current_user.admin?
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        redirect_to root_path
      else
        render 'new'
      end
    else
      redirect_to root_path
    end
  end

  def update
    if current_user && current_user.admin?
      @article = Article.find(params[:id])
      if @article.update(article_params)
        redirect_to root_path
      else
        render 'edit'
      end
    else
      redirect_to root_path
    end
  end

  def edit
    if current_user && current_user.admin?
      @article = Article.find(params[:id])
        render 'edit'
      else
        redirect_to root_path
      end
  end

  def destroy
    if current_user && current_user.admin?
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to root_path
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/articles_helper.rb
# Articles Helper. Does nothing at the moment.
module ArticlesHelper
end

app/views/articles/_add_comment.html.haml
.center.jumbotron.dark
  %h2.pull-left Add a comment
  = form_for([@article, @article.comments.build]) do |f|
    %p=f.text_area :body, {class: 'grey-text-area form-control', rows: '3'}
    =f.submit
  

app/views/articles/_edit_article_form.html.haml
.container
  .center.jumbotron.dark
    %h1 Edit Article
  .center.jumbotron.dark
    =form_for :article, url: article_path(@article), method: :patch do |f|
      .field
        %p.pull-left=f.label :title
        = f.text_field :title, {class: 'grey-text-area form-control'}
      .field
        %p.pull-left=f.label :title
        =f.text_area :text, {class: 'grey-text-area form-control', rows: '10'}
      =f.submit 'Update', class: 'btn btn-primary green-btn', data: {confirm: 'Are you sure you want to save these changes?'}

app/views/articles/_new_article_form.html.haml
.container
  .center.jumbotron.dark
    %h1 New Article
  .center.jumbotron.dark
    = form_for :article, url: articles_path do |f|
      .field
        %p.pull-left= f.label :title
        = f.text_field :title, {class: 'grey-text-area'}
      .field
        %p.pull-left= f.label :text
        = f.text_area :text, {class: 'grey-text-area', rows: '10'}
      = f.submit "Create", class: 'btn btn-primary green-btn',          |
        data: {confirm: 'Are you sure you want to save these changes?'} |

app/views/articles/_show_article.html.haml
.container
  .center.jumbotron.dark
    %h1
      %strong Title:
      = @article.title
  .center.jumbotron.dark
    %p
      %strong Contents:
      %br/
      = @article.text
    %small
      Created by #{@article.user.name} at #{@article.created_at}
    - if current_user && current_user.admin?
      = button_to 'Modify', edit_article_path(@article), {method: :get, class: 'btn btn-primary green-btn'}
      = button_to 'Delete', article_path(@article), { method: :delete, class: 'btn btn-primary green-btn', data: {confirm: 'Are you sure you want to delete this article?'}}

app/views/articles/_show_comments.html.haml
.center.jumbotron.dark
  %h2 Comments
.center.jumbotron.dark
  - @article.comments.each do |comment|
    %p
      %strong= comment.user.name
    %p= comment.body
    - if current_user && current_user.admin?
      = button_to 'X', article_comment_path(comment.article, comment), { method: :delete, class: 'btn btn-primary green-btn pull-right', data: {confirm: 'Are you sure you want to delete your comment?'}}
    %div
      %small
        Created at #{comment.created_at}
    %hr/

app/views/articles/edit.html.haml
- if current_user && current_user.admin?
  - provide(:title, 'Article - Edit')
  = render 'edit_article_form'

app/views/articles/new.html.haml
- if current_user && current_user.admin?
  - provide(:title, 'Article - New')
  = render 'new_article_form'

app/views/articles/show.html.haml
= render 'show_article'
= render 'show_comments'
- if current_user
  = render 'add_comment'