config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'users_controller/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show] do
    member {post :link_spotify}
  end
  resources :playlists, only: [:new, :show]
  resources :bugs
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  root 'pages#home'
  post 'playlists/display' => 'playlists#display', as: :display_playlist

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/help',    to: 'pages#help'
  get  '/callback', to: 'pages#callback'
  get '/positivity', to: 'pages#show_positivity'
  get '/slack', to: 'pages#send_to_slack'

  get '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
  post '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
end

app/views/pages/_positivity_table.html.haml
.center.jumbotron.dark
  %table.table
    %thead
      %tr
        %th Rank
        %th Name
        %th Positivity Score
        %th Old Positivity Score
        %th
          Up
          %i.fa.fa-arrow-up{'aria-hidden' => 'true'}
          = succeed '/' do
            Down
            %i.fa.fa-arrow-down{'aria-hidden' => 'true'}
          = succeed '/' do
            Same
            %i.fa.fa-arrows-h{'aria-hidden' => 'true'}
    %tbody
      - i = 0
      - @users.each do |u|
        - if u.positivity_score?
          %tr
            %td=i += 1
            %td=u.name
            %td #{(u.positivity_score * 100).round(2)}/100
            - if u.old_positivity_score?
              %td #{(u.old_positivity_score * 100).round(2)}/100
            - else
              %td N/A
            %td
              - if u.old_positivity_score?
                - if u.positivity_score > u.old_positivity_score
                  %i.fa.fa-arrow-up{'aria-hidden' => 'true'}
                - elsif u.positivity_score < u.old_positivity_score
                  %i.fa.fa-arrow-down{'aria-hidden' => 'true'}
                - elsif u.positivity_score == u.old_positivity_score
                  %i.fa.fa-arrows-h{'aria-hidden' => 'true'}
              - else
                N/A

app/views/pages/_show_article.html.haml
- @articles.each do |article|
  .center.jumbotron.dark
    %h3=article.title
    %p=article.text
    %div
      %small Created by #{article.user.name} at #{article.created_at}
    %div
      %p #{article.comments.count} comments.
    %div
      = button_to 'View', article_path(article), {method: :get, class: 'btn btn-primary green-btn'}
      - if current_user && current_user.admin?
        = button_to 'Modify', edit_article_path(article), {method: :get, class: 'btn btn-primary green-btn'}
        = button_to 'Delete', article_path(article), {method: :delete, class: 'btn btn-primary green-btn', data: {confirm: 'Are you sure you want to delete this article?'}}

app/views/pages/about.html.haml
- provide(:title, 'About')
.container
  .center.jumbotron.dark
    %h1 About
  .center.jumbotron.dark
    %p SongSpot was created using Ruby on Rails. Recommendations are based on Songs provided by you. These come directly from Spotify's API

app/views/pages/contact.html.haml
- provide(:title, 'Contact')
.container
  .center.jumbotron.dark
    %h1 Contact
  .center.jumbotron.dark
    %p
      Contact me over at
      = succeed '.' do
        %a{:href => 'http://www.carlgreenwood.co.uk' }http://www.carlgreenwood.co.uk

app/views/pages/help.html.haml
- provide(:title, "Help")
.container
  .center.jumbotron.dark
    %h1 Help
  .center.jumbotron.dark
    %p WIP
  .center.dark.header
    %h2 How to link to Spotify
  %ol.pull-left
    .center.dark.header
      %li.header Create an account or login
      .center.jumbotron.dark.content
        %ul.pull-left
          %li Click Log In/Sign up in the top right corner of the page.
          %li If you've amde an acccount please sign in.
          %small If you've forgotten your password please click the 'Forgotten your password?' link
          %li Otherwise please create an account by filling in all the fields on the page.
    .center.dark.header
      %li Go to your Profile page.
      %ul.content
        %li Click your name in the top right corner of the page.

app/views/pages/home.html.haml
- provide(:title, "Home")
.container
  - if current_user
    %marquee.center.dark
      %p WARNING - Due to changes to the Application's permission's please relink your acccount to Spotify from the user page. - WARNING
  - else
    %marquee.center.dark
      %p Welcome to the SongSpot application
  .center.jumbotron.dark
    %h1 Welcome to SongSpot
    %p This is the home page for the SongSpot application.
  = render 'show_article'
  - if current_user && current_user.admin?
    .center.jumbotron.dark
      = button_to 'New Article', new_article_path, {method: :get, class: 'btn btn-primary green-btn'}

app/views/pages/show_positivity.html.haml
- provide(:title, 'Positivity Rankings')
.container
  .center.jumbotron.dark
    %h1 Positivity
    - if current_user && current_user.positivity_score?
      %h3 Your Positivity Score: #{(current_user.positivity_score * 100).round(2)}/100
  = render 'positivity_table'
  .center.jumbotron.dark
    - if current_user && current_user.admin?
      = button_to 'Send to Slack', slack_path,{ method: :get, class: 'btn btn-primary green-btn'}