config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'users_controller/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show] do
    member {post :link_spotify}
  end
  resources :playlists, only: [:new, :show]
  resources :bugs
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  root 'pages#home'
  post 'playlists/display' => 'playlists#display', as: :display_playlist

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/help',    to: 'pages#help'
  get  '/callback', to: 'pages#callback'
  get '/positivity', to: 'pages#show_positivity'
  get '/slack', to: 'pages#send_to_slack'

  get '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
  post '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
end

app/models/bug.rb
#
class Bug < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5, maximum: 128 }
  validates :content, presence: true, length: { minimum: 5, maximum: 5000 }
  validates :bug_type, presence: true
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def new
    @bug = Bug.new
  end

  def index
    if current_user
      @bugs = Bug.all
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def create
    @bug = Bug.new(bug_params)
    @bug.user = current_user
    if @bug.save
      redirect_to bugs_path
    else
      render 'new'
    end
  end

  def update
    if current_user && current_user.admin?
      @bug = Bug.find(params[:id])
      if @bug.update(bug_params)
        redirect_to bugs_path
      else
        render 'edit'
      end
    else
      redirect_to root_path
    end
  end

  def edit
    if current_user && current_user.admin?
      @bug = Bug.find(params[:id])
        render 'edit'
      else
        redirect_to root_path
      end
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    redirect_to bugs_path
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :bug_type, :content, :bug_status)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_new_bug_form.html.haml
.container
  .center.jumbotron.dark
    %h1 Report a bug
  .center.jumbotron.dark
    = form_for :bug, url: bugs_path do |f|
      - if @bug.errors.any?
        #error_explanation
          %ul.pull-left
            - @bug.errors.full_messages.each do |msg|
              %li= msg
      .field
        %p.pull-left= f.label :title
        = f.text_field :title, {class: 'grey-text-area'}
      .field
        %p.pull-left= f.label :type
        = f.select(:bug_type, ["Playlist creation","User registration","Site navigation", |
          "Report a bug"])                                                                |
      .field
        %p.pull-left= f.label :content
        = f.text_area :content, {class: 'grey-text-area',rows: '5'}
      = f.submit 'Create', class: 'btn btn-primary green-btn'

app/views/bugs/edit.html.erb
<% if current_user && (current_user.id == @bug.user_id || current_user.admin?)%>
<% provide(:title, 'Bug - New') %>
<h1>Edit the bug</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :bug, url: bug_path(@bug), method: :patch do |f| %>

    <% if @bug.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@bug.errors.count, "error") %> prohibited
            this bug from being saved:
          </h2>
          <ul>
            <% @bug.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title%>
    </div>

    <% if current_user.admin? %>
    <div class="field">
      <%= f.label :bug_status %><br />
      <%= f.select(:bug_status,["Pending","Resolved","Unsolved"]) %>
      </div>
      <% end %>

    <div class="field">
      <%= f.label :type %><br />
      <p>
      <%= f.select(:bug_type, ["Playlist creation","User registration","Site navigation",
                           "Report a bug"])%>
    </div>




    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content%>
    </div>


    <%= f.submit "Update", class: 'btn btn-primary' %>
    <% end %>


  </div>
</div>
<% end %>

app/views/bugs/index.html.erb
<% provide(:title, 'My Bugs') %>
<h1>Bug Manager</h1>
<div class="container">
  <h3>My Bugs</h3>
  <% @bugs.each do |bug| %>
  <% if current_user && current_user.id == bug.user_id %>
  <div class="bug_post <%= bug.bug_status %>">

    <h3><%= bug.title %></h3>
    <h2>Bug Type: <strong><%= bug.bug_type %></strong>
      Bug Status: <strong><%= bug.bug_status %></strong></h2>
    <p><%= bug.content %></p>
    <p class="pull-right">
      <button type="button" class="btn btn-primary">
        <%= link_to 'Show', bug %>
      </button>
      <button type="button" class="btn btn-primary">
        <%= link_to 'Edit', edit_bug_path(bug) %>
      </button>
      <button type="button" class="btn btn-primary">
        <%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %>
      </button>
  </div>
  <% end %>
  <% end %>

<% if current_user && current_user.admin? %>
  <h3>All Bugs</h3>
  <% @bugs.each do |bug| %>
  <div class="bug_post <%= bug.bug_status %>">
    <h3><%= bug.title %></h3>
    <h2>Bug Type: <strong><%= bug.bug_type %></strong>
      Bug Status: <strong><%= bug.bug_status %></strong></h2>
    <p><%= bug.content %></p>
    <p class="pull-right">
      <button type="button" class="btn btn-primary">
        <%= link_to 'Show', '#' %>
      </button>
      <button type="button" class="btn btn-primary">
        <%= link_to 'Edit', edit_bug_path(bug) %>
      </button>
      <button type="button" class="btn btn-primary">
        <%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %>
      </button>
    </p>
  </div>
  <% end %>

  <% end %>
</div>

app/views/bugs/new.html.erb
<% provide(:title, 'Bug - New') %>
<% if current_user%>
  <%= render 'new_bug_form' %>
<% end %>

app/views/bugs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @bug.title %>
  <strong>Bug Type:</strong>
  <%= @bug.bug_type %>
</p>
<p>
  <strong>Bug Status:</strong>
  <marquee direction="right" class="<%= @bug.bug_status %>"><%= @bug.bug_status %></marquee>
</p>

  <strong>Description:</strong>
  <%= @bug.content %>
</p>
<p>
  <marquee class="<%= @bug.bug_status %>"><%= @bug.bug_status %></marquee>
</p>
<small>Created by <%= @bug.user.name %> at <%= @bug.created_at %>
</small>
<% if current_user && current_user.admin? %>
<button type="button" class="btn btn-primary pull-right">
  <%= link_to 'Modify', edit_bug_path(@bug) %>
</button>
<button type="button" class="btn btn-primary pull-right">
  <%= link_to 'Delete', bug_path(@bug),
      method: :delete,
      data: { confirm: 'Are you sure you want
                        to delete this article?' } %>
                      </button>
                        <% end %>
                        <marquee class="<%= @bug.bug_status %>" direction="down" width="1000" height="100" behavior="alternate" style="border:solid">
  <marquee behavior="alternate">
    <%= @bug.bug_status %>
  </marquee>
</marquee>