config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'users_controller/show'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show] do
    member {post :link_spotify}
  end
  resources :playlists, only: [:new, :show]
  resources :bugs
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  root 'pages#home'
  post 'playlists/display' => 'playlists#display', as: :display_playlist

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/help',    to: 'pages#help'
  get  '/callback', to: 'pages#callback'
  get '/positivity', to: 'pages#show_positivity'
  get '/slack', to: 'pages#send_to_slack'

  get '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
  post '/add_track_to_your_music', to: 'playlists#add_track_to_your_music'
end

app/views/layouts/_footer.html.haml
%footer.footer
  .jumbotron.dark
    %small
      SongSpot by
      %a{:href => 'http://www.carlgreenwood.co.uk/'}Carl Greenwood
    %nav
      %ul
        %li= link_to 'About', about_path
        %li= link_to 'Contact', contact_path
        %li= link_to 'Report a bug', new_bug_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "SongSpot", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",   root_path
        %li= link_to "Help",   help_path
        %li= link_to "Positivity Scores", positivity_path
        %li= link_to "Playlist", new_playlist_path
        %li
          %ul.nav.navbar-nav.pull-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  = current_user.name
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li= link_to 'Profile', user_path(current_user)
                  %li= link_to 'My Bugs', bugs_path
                  %li= link_to 'Log out', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Log In', new_user_session_path
              %li= link_to 'Sign Up', new_user_registration_path

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title=full_title(yield(:title))
    %script{:src => 'https://use.fontawesome.com/d95b3f22fd.js'}
    %link{:href => 'https://fonts.googleapis.com/css?family=Open+Sans', :rel => 'stylesheet', :type => 'text/css'}
    = render 'layouts/rails_default'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'